let slideIndex=1;const slides=document.querySelectorAll(".mySlides"),dots=document.querySelectorAll(".dot"),totalSlides=slides.length-2,sliderTrack=document.querySelector(".slider-track");function showSlides(e){slideIndex=e,e===totalSlides+1?(sliderTrack.style.transition="none",sliderTrack.style.transform="translateX(-100%)",slideIndex=1,setTimeout(()=>{sliderTrack.style.transition="transform 0.5s ease-in-out"},20)):0===e&&(sliderTrack.style.transition="none",sliderTrack.style.transform=`translateX(-${100*totalSlides}%)`,slideIndex=totalSlides,setTimeout(()=>{sliderTrack.style.transition="transform 0.5s ease-in-out"},20));let s=-(100*slideIndex);sliderTrack.style.transform=`translateX(${s}%)`,dots.forEach((e,s)=>{e.className=e.className.replace(" active",""),s===slideIndex-1&&(e.className+=" active")})}function nextSlide(){showSlides(slideIndex+1)}sliderTrack.style.transform="translateX(-100%)";let autoSlide=setInterval(nextSlide,3e3);dots.forEach((e,s)=>{e.addEventListener("click",()=>{clearInterval(autoSlide),showSlides(s+1),autoSlide=setInterval(nextSlide,3e3)})}),showSlides(slideIndex);const rssFeeds=["https://www.physicstoday.org/rss","https://www.sciencenews.org/feed/","https://www.sciencedaily.com/rss/top/science.xml","https://www.nasa.gov/rss/dyn/breaking_news.rss","https://arstechnica.com/science/feed/","https://www.newscientist.com/feed/home/","https://phys.org/rss-feed/breaking/","https://www.nature.com/nature.rss"],validTopicsSet=new Set(["quantum","gravitational","waves","exoplanet","discovery","dark","matter","black","hole","science","physics","astrophysics","technology","innovation","research","biology","chemistry","medicine","genetics","environment","energy","black hole"]),newsItems=[],fetchRSSFeeds=async()=>{let e="",s={};for(let t of rssFeeds)try{let r=await fetch(`https://api.rss2json.com/v1/api.json?rss_url=${encodeURIComponent(t)}`),n=await r.json();"ok"===n.status?n.items.forEach(t=>{newsItems.push(t),e+=`
                        <div class="news-item">
                            <img src="${t.enclosure?t.enclosure.link:"default-image.jpg"}" alt="News Image">
                            <h2>${t.title}</h2>
                            <p>${t.description}</p>
                            <a href="${t.link}" class="read-more" target="_blank">Read More</a>
                        </div>
                    `;let r=t.title.split(" ");r.forEach(e=>{let r=e.replace(/[^\w]/g,"").toLowerCase();validTopicsSet.has(r)&&r.length>3&&(s[t.link]=(s[t.link]||0)+1)})}):console.error("Error fetching feed:",n.message)}catch(i){console.error("Fetch error:",i)}document.querySelector(".news-grid").innerHTML=e;let l=Object.entries(s).sort((e,s)=>s[1]-e[1]).slice(0,5).map(([e])=>newsItems.find(s=>s.link===e));updateTrendingNews(l)},updateTrendingNews=e=>{let s=document.getElementById("trending-topics");s.innerHTML="",e.forEach(e=>{let t=document.createElement("li"),r=document.createElement("a");r.href=e.link,r.textContent=e.title,t.appendChild(r),s.appendChild(t)})},searchButton=document.getElementById("search-button"),searchInput=document.getElementById("search-input");searchButton.addEventListener("click",()=>{let e=searchInput.value.toLowerCase(),s=newsItems.filter(s=>s.title.toLowerCase().includes(e)||s.description.toLowerCase().includes(e));document.querySelector(".news-grid").innerHTML="",s.forEach(e=>{let s=`
            <div class="news-item">
                <img src="${e.enclosure?e.enclosure.link:"default-image.jpg"}" alt="News Image">
                <h2>${e.title}</h2>
                <p>${e.description}</p>
                <a href="${e.link}" class="read-more" target="_blank">Read More</a>
            </div>
        `;document.querySelector(".news-grid").innerHTML+=s}),searchInput.value=""}),fetchRSSFeeds();
